# USER SCHEMA

# --- !Ups
CREATE TABLE  USERS  (
id SERIAL PRIMARY KEY,
first_name VARCHAR (100) NOT NULL,
last_name VARCHAR (100) NOT NULL,
mobile BIGINT NOT NULL,
email VARCHAR (100) NOT NULL,
birth_date BIGINT DEFAULT NULL
);

# --- !Downs
DROP TABLE IF EXISTS USERS;